"use client";
import { useMemo, useState } from "react";
import { SiteHeader } from "@/components/site-header";
import { Footer } from "@/components/footer";
import { calculateReadiness, readinessDimensions } from "@/lib/calculations";
import { saveReadiness, submitReadinessLead } from "@/app/tools/actions";

export default function Readiness() {
 const [scores,setScores] = useState<Record<string,number>>(Object.fromEntries(readinessDimensions.map(d=>[d,3])));
 const result = useMemo(()=>calculateReadiness(Object.values(scores)),[scores]);
 return <><SiteHeader/><main className="tool-page shell"><span className="kicker">AI readiness assessment</span><h1>Understand what must be true before AI can create value.</h1><p className="lede">Score six practical dimensions from 1 to 5. Save the result to your workspace or share it with QgritAI to discuss the next step.</p><section className="tool-grid"><form className="panel assessment" action={saveReadiness}>{readinessDimensions.map(d=><label key={d}><span>{d}<b>{scores[d]}/5</b></span><input name={d} type="range" min="1" max="5" value={scores[d]} onChange={e=>setScores({...scores,[d]:Number(e.target.value)})}/></label>)}<button className="button">Save to workspace</button></form><aside className="score-card"><span>Readiness score</span><strong>{result.total}</strong><h2>{result.label}</h2><p>{result.total >= 60 ? "Select one high-value workflow, establish baseline measures, and validate it through a controlled pilot." : "Strengthen ownership, process clarity, data access, and governance before committing to a large implementation."}</p></aside></section><section className="readiness-contact"><div><span className="kicker">Discuss your result</span><h2>Turn this score into a focused action plan.</h2><p>Share your context and current scores with QgritAI. You do not need an account.</p></div><form action={submitReadinessLead} className="panel workspace-form">{readinessDimensions.map(d=><input key={d} type="hidden" name={d} value={scores[d]}/>) }<label>Full name<input name="fullName" required minLength={2} autoComplete="name"/></label><label>Work email<input name="workEmail" required type="email" autoComplete="email"/></label><label>Company<input name="company" required minLength={2} autoComplete="organization"/></label><label>Job title<input name="jobTitle" autoComplete="organization-title"/></label><label className="form-wide">What outcome are you working toward?<textarea name="message" required minLength={20} maxLength={3000} rows={5}/></label><label className="form-trap" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label><button className="button">Share result</button></form></section></main><Footer/></>;
}
