import { Bot, BrainCircuit, CalendarDays, ChartNoAxesCombined, CloudCog, Code2, Compass, Gauge, RefreshCw, Search, ShieldCheck, Workflow } from "lucide-react";
import { CallToAction, PageHero, SectionIntro } from "@/components/marketing";
import { Footer } from "@/components/footer";
import { SiteHeader } from "@/components/site-header";

export const metadata = { title: "AI transformation services", description: "AI strategy, agentic automation, AI agents, intelligent applications, governance, and managed AI operations from QgritAI." };

const services = [
  { icon: Compass, label: "Strategy", title: "AI opportunity and transformation strategy", description: "Understand where AI can improve the business before investing in technology.", items: ["Executive and functional workshops", "Workflow and opportunity mapping", "Readiness and risk assessment", "Prioritized roadmap and business cases"] },
  { icon: Workflow, label: "Automation", title: "Agentic workflow automation", description: "Turn fragmented, repetitive work into controlled end-to-end workflows.", items: ["Document and email workflows", "Approvals and exception handling", "CRM, service, and operations automation", "Human review and escalation paths"] },
  { icon: Bot, label: "Agents", title: "Business agents and knowledge systems", description: "Give teams focused digital collaborators with the right context, tools, and boundaries.", items: ["Research and intelligence agents", "Customer and employee support agents", "Sales and operations agents", "Enterprise knowledge assistants"] },
  { icon: Code2, label: "Applications", title: "AI-enabled products and internal tools", description: "Build software around the workflow when chat alone is not the right interface.", items: ["Internal operations applications", "Client and customer experiences", "Decision-support tools", "AI-native product development"] },
  { icon: ShieldCheck, label: "Adoption", title: "Governance, assurance, and adoption", description: "Create the controls and operating practices required for trustworthy use.", items: ["Permissions and approval design", "Evaluation and quality frameworks", "Security and auditability", "Training and operating-model adoption"] },
  { icon: Gauge, label: "Operations", title: "Managed AI operations", description: "Keep deployed capabilities reliable, economical, useful, and aligned as conditions change.", items: ["Performance and cost monitoring", "Prompt, workflow, and model improvement", "Incident and exception management", "Value and adoption reporting"] },
];

export default function SolutionsPage() {
  return <><SiteHeader/><main><PageHero eyebrow="Services" title="AI services shaped around real business work." description="From the first strategy conversation through implementation and ongoing operations, QgritAI assembles the right agent capabilities around the outcome you need."/>
  <section className="section shell page-section"><div className="detail-service-list">{services.map(({ icon: Icon, label, title, description, items }) => <article className="detail-service" key={title}><div className="detail-service-copy"><div className="icon-box"><Icon/></div><span className="kicker">{label}</span><h2>{title}</h2><p>{description}</p></div><ul>{items.map(item => <li key={item}>{item}</li>)}</ul></article>)}</div></section>
  <section className="section light-section offer-section"><div className="shell"><SectionIntro eyebrow="Ways to work together" title="A clear first engagement, not an open-ended transformation program." description="Choose the starting point that matches your current level of clarity. Scope and timing are confirmed after the initial conversation."/><div className="offer-grid"><article><div className="offer-top"><Search/><span>01</span></div><small>Typically 1–2 weeks</small><h3>AI Opportunity Sprint</h3><p className="offer-for">For leaders who know AI matters but need clarity on where to begin.</p><ul><li>Business and workflow discovery</li><li>Prioritized opportunity map</li><li>Readiness, risk, and dependency review</li><li>Value thesis and recommended roadmap</li></ul><a href="/contact">Discuss an opportunity sprint →</a></article><article><div className="offer-top"><CalendarDays/><span>02</span></div><small>Typically 3–6 weeks</small><h3>Agentic Proof of Value</h3><p className="offer-for">For teams with a credible workflow and a decision that requires working evidence.</p><ul><li>Focused solution and control design</li><li>Working agent or automation</li><li>Evaluation with representative scenarios</li><li>Implementation and adoption recommendation</li></ul><a href="/contact">Explore a proof of value →</a></article><article><div className="offer-top"><RefreshCw/><span>03</span></div><small>Ongoing engagement</small><h3>Managed AI Operations</h3><p className="offer-for">For businesses that want deployed AI capabilities operated and improved continuously.</p><ul><li>Reliability, quality, and cost monitoring</li><li>Workflow, prompt, and model improvement</li><li>Incident and exception management</li><li>Adoption and value reporting</li></ul><a href="/contact">Discuss managed operations →</a></article></div><p className="offer-note">Engagement duration varies with workflow complexity, data access, integrations, controls, and stakeholder availability.</p></div></section>
  <section className="section contrast-section"><div className="shell"><SectionIntro eyebrow="Flexible scope" title="One workflow, one function, or a broader transformation." description="The engagement begins at the smallest scope that can produce credible evidence. Successful capabilities can then expand without committing to a large program upfront."/><div className="scope-grid"><article><Search/><h3>Opportunity sprint</h3><p>Clarify the problem, evidence, feasibility, risks, and recommended first move.</p></article><article><BrainCircuit/><h3>Proof of value</h3><p>Build a controlled working capability and test it with real users and workflows.</p></article><article><CloudCog/><h3>Implementation</h3><p>Integrate the solution, harden operations, train users, and prepare ownership.</p></article><article><ChartNoAxesCombined/><h3>Managed improvement</h3><p>Operate, measure, and improve the system through an ongoing service.</p></article></div></div></section><CallToAction/></main><Footer/></>;
}
